/*
    bmarkdiff is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bmarkdiff is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bmarkdiff.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.17.0

#include <stan/model/model_header.hpp>

namespace model_mark_diff_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_mark_diff");
    reader.add_event(29, 29, "end", "model_mark_diff");
    return reader;
}

#include <meta_header.hpp>
 class model_mark_diff : public prob_grad {
private:
    int N;
    int n_ctrl;
    int n_case;
    vector<int> case_counts;
    vector<int> ctrl_counts;
public:
    model_mark_diff(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_mark_diff(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_mark_diff_namespace::model_mark_diff";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n_ctrl", "int", context__.to_vec());
            n_ctrl = int(0);
            vals_i__ = context__.vals_i("n_ctrl");
            pos__ = 0;
            n_ctrl = vals_i__[pos__++];
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "n_case", "int", context__.to_vec());
            n_case = int(0);
            vals_i__ = context__.vals_i("n_case");
            pos__ = 0;
            n_case = vals_i__[pos__++];
            current_statement_begin__ = 5;
            validate_non_negative_index("case_counts", "N", N);
            context__.validate_dims("data initialization", "case_counts", "int", context__.to_vec(N));
            validate_non_negative_index("case_counts", "N", N);
            case_counts = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("case_counts");
            pos__ = 0;
            size_t case_counts_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < case_counts_limit_0__; ++i_0__) {
                case_counts[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 6;
            validate_non_negative_index("ctrl_counts", "N", N);
            context__.validate_dims("data initialization", "ctrl_counts", "int", context__.to_vec(N));
            validate_non_negative_index("ctrl_counts", "N", N);
            ctrl_counts = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("ctrl_counts");
            pos__ = 0;
            size_t ctrl_counts_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < ctrl_counts_limit_0__; ++i_0__) {
                ctrl_counts[i_0__] = vals_i__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 2;
            check_greater_or_equal(function__,"N",N,0);
            current_statement_begin__ = 3;
            check_greater_or_equal(function__,"n_ctrl",n_ctrl,0);
            current_statement_begin__ = 4;
            check_greater_or_equal(function__,"n_case",n_case,0);
            current_statement_begin__ = 5;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"case_counts[k0__]",case_counts[k0__],0);
            }
            current_statement_begin__ = 6;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"ctrl_counts[k0__]",ctrl_counts[k0__],0);
            }
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 9;
            validate_non_negative_index("case_p", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 10;
            validate_non_negative_index("ctrl_p", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 11;
            ++num_params_r__;
            current_statement_begin__ = 12;
            ++num_params_r__;
            current_statement_begin__ = 13;
            ++num_params_r__;
            current_statement_begin__ = 14;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_mark_diff() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("case_p")))
            throw std::runtime_error("variable case_p missing");
        vals_r__ = context__.vals_r("case_p");
        pos__ = 0U;
        validate_non_negative_index("case_p", "N", N);
        context__.validate_dims("initialization", "case_p", "vector_d", context__.to_vec(N));
        vector_d case_p(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            case_p(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lub_unconstrain(0,1,case_p);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable case_p: ") + e.what());
        }

        if (!(context__.contains_r("ctrl_p")))
            throw std::runtime_error("variable ctrl_p missing");
        vals_r__ = context__.vals_r("ctrl_p");
        pos__ = 0U;
        validate_non_negative_index("ctrl_p", "N", N);
        context__.validate_dims("initialization", "ctrl_p", "vector_d", context__.to_vec(N));
        vector_d ctrl_p(static_cast<Eigen::VectorXd::Index>(N));
        for (int j1__ = 0U; j1__ < N; ++j1__)
            ctrl_p(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lub_unconstrain(0,1,ctrl_p);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable ctrl_p: ") + e.what());
        }

        if (!(context__.contains_r("ctrl_a")))
            throw std::runtime_error("variable ctrl_a missing");
        vals_r__ = context__.vals_r("ctrl_a");
        pos__ = 0U;
        context__.validate_dims("initialization", "ctrl_a", "double", context__.to_vec());
        double ctrl_a(0);
        ctrl_a = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,ctrl_a);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable ctrl_a: ") + e.what());
        }

        if (!(context__.contains_r("ctrl_b")))
            throw std::runtime_error("variable ctrl_b missing");
        vals_r__ = context__.vals_r("ctrl_b");
        pos__ = 0U;
        context__.validate_dims("initialization", "ctrl_b", "double", context__.to_vec());
        double ctrl_b(0);
        ctrl_b = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,ctrl_b);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable ctrl_b: ") + e.what());
        }

        if (!(context__.contains_r("case_a")))
            throw std::runtime_error("variable case_a missing");
        vals_r__ = context__.vals_r("case_a");
        pos__ = 0U;
        context__.validate_dims("initialization", "case_a", "double", context__.to_vec());
        double case_a(0);
        case_a = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,case_a);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable case_a: ") + e.what());
        }

        if (!(context__.contains_r("case_b")))
            throw std::runtime_error("variable case_b missing");
        vals_r__ = context__.vals_r("case_b");
        pos__ = 0U;
        context__.validate_dims("initialization", "case_b", "double", context__.to_vec());
        double case_b(0);
        case_b = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,case_b);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable case_b: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<T__> in__(params_r__,params_i__);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  case_p;
            (void) case_p;  // dummy to suppress unused var warning
            if (jacobian__)
                case_p = in__.vector_lub_constrain(0,1,N,lp__);
            else
                case_p = in__.vector_lub_constrain(0,1,N);

            Eigen::Matrix<T__,Eigen::Dynamic,1>  ctrl_p;
            (void) ctrl_p;  // dummy to suppress unused var warning
            if (jacobian__)
                ctrl_p = in__.vector_lub_constrain(0,1,N,lp__);
            else
                ctrl_p = in__.vector_lub_constrain(0,1,N);

            T__ ctrl_a;
            (void) ctrl_a;  // dummy to suppress unused var warning
            if (jacobian__)
                ctrl_a = in__.scalar_lb_constrain(0,lp__);
            else
                ctrl_a = in__.scalar_lb_constrain(0);

            T__ ctrl_b;
            (void) ctrl_b;  // dummy to suppress unused var warning
            if (jacobian__)
                ctrl_b = in__.scalar_lb_constrain(0,lp__);
            else
                ctrl_b = in__.scalar_lb_constrain(0);

            T__ case_a;
            (void) case_a;  // dummy to suppress unused var warning
            if (jacobian__)
                case_a = in__.scalar_lb_constrain(0,lp__);
            else
                case_a = in__.scalar_lb_constrain(0);

            T__ case_b;
            (void) case_b;  // dummy to suppress unused var warning
            if (jacobian__)
                case_b = in__.scalar_lb_constrain(0,lp__);
            else
                case_b = in__.scalar_lb_constrain(0);


            // transformed parameters



            // validate transformed parameters

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // model body

            current_statement_begin__ = 17;
            lp_accum__.add(gamma_log<propto__>(ctrl_a, 20, 20));
            current_statement_begin__ = 18;
            lp_accum__.add(gamma_log<propto__>(ctrl_b, 20, 20));
            current_statement_begin__ = 19;
            lp_accum__.add(gamma_log<propto__>(case_a, 20, 20));
            current_statement_begin__ = 20;
            lp_accum__.add(gamma_log<propto__>(case_b, 20, 20));
            current_statement_begin__ = 21;
            lp_accum__.add(beta_log<propto__>(ctrl_p, ctrl_a, ctrl_b));
            current_statement_begin__ = 22;
            lp_accum__.add(beta_log<propto__>(case_p, case_a, case_b));
            current_statement_begin__ = 23;
            lp_accum__.add(binomial_log<propto__>(case_counts, n_case, case_p));
            current_statement_begin__ = 24;
            lp_accum__.add(binomial_log<propto__>(ctrl_counts, n_ctrl, ctrl_p));

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("case_p");
        names__.push_back("ctrl_p");
        names__.push_back("ctrl_a");
        names__.push_back("ctrl_b");
        names__.push_back("case_a");
        names__.push_back("case_b");
        names__.push_back("case_ctrl_diff");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "model_mark_diff_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d case_p = in__.vector_lub_constrain(0,1,N);
        vector_d ctrl_p = in__.vector_lub_constrain(0,1,N);
        double ctrl_a = in__.scalar_lb_constrain(0);
        double ctrl_b = in__.scalar_lb_constrain(0);
        double case_a = in__.scalar_lb_constrain(0);
        double case_b = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(case_p[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(ctrl_p[k_0__]);
            }
        vars__.push_back(ctrl_a);
        vars__.push_back(ctrl_b);
        vars__.push_back(case_a);
        vars__.push_back(case_b);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {



            // validate transformed parameters

            // write transformed parameters

            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 27;
            validate_non_negative_index("case_ctrl_diff", "N", N);
            vector_d case_ctrl_diff(static_cast<Eigen::VectorXd::Index>(N));
            (void) case_ctrl_diff;  // dummy to suppress unused var warning

            stan::math::initialize(case_ctrl_diff, std::numeric_limits<double>::quiet_NaN());
            stan::math::fill(case_ctrl_diff,DUMMY_VAR__);


            current_statement_begin__ = 28;
            stan::math::assign(case_ctrl_diff, subtract(case_p,ctrl_p));

            // validate generated quantities
            current_statement_begin__ = 27;

            // write generated quantities
            for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(case_ctrl_diff[k_0__]);
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_mark_diff";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "case_p" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ctrl_p" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "ctrl_a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ctrl_b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "case_a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "case_b";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "case_ctrl_diff" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "case_p" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "ctrl_p" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "ctrl_a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ctrl_b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "case_a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "case_b";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "case_ctrl_diff" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
    }

}; // model

}

typedef model_mark_diff_namespace::model_mark_diff stan_model;


#endif
